import sys
from PyQt5.QtWidgets import (QDialog,QHBoxLayout,QLabel,QApplication,
                             QVBoxLayout,QTextEdit,QPushButton,QTextBrowser,
                             QComboBox,QPlainTextEdit)
import qdarkstyle
from PyQt5.QtGui import QIcon,QPixmap,QFont


class MultiIndexSelection(QDialog):
    def __init__(self):
        super(MultiIndexSelection,self).__init__()
        self.initUI()

    def initUI(self):
        self.index = ["CCI","RSI","KDJ"]
        self.sign = ["大于","小于","等于","不小于","不大于","不等于"]

        self.resize(700,500)
        self.setWindowTitle("QUANT XH 金融终端")
        self.setWindowIcon(QIcon("static/icon.png"))

        self.poollabel = QLabel()
        self.poollabel.setText("股票池")
        self.poollabel.setFont(QFont("仿宋", 15))
        self.pooledit = QTextEdit()
        self.pooledit.setFont(QFont("仿宋", 12))
        self.pooledit.setFixedSize(120,30)
        self.pooladdbtn = QPushButton()
        self.pooladdbtn.setText("添加股票")
        self.pooladdbtn.setFont(QFont("仿宋", 12))
        self.pooladdbtn.setFixedSize(100,30)
        self.poolclbtn = QPushButton()
        self.poolclbtn.setText("清空")
        self.poolclbtn.setFont(QFont("仿宋", 12))
        self.poolclbtn.setFixedSize(80, 30)
        self.pooltb = QTextBrowser()
        self.pooltb.setFixedSize(300,300)

        self.buylabel = QLabel()
        self.buylabel.setText("买入条件")
        self.buylabel.setFont(QFont("仿宋", 13))
        self.buycomboindex = QComboBox()
        self.buycomboindex.addItems(self.index)
        self.buycomboindex.setFixedWidth(40)
        self.buycomboindex.setFont(QFont("仿宋", 10))
        self.buycombosign = QComboBox()
        self.buycombosign.addItems(self.sign)
        self.buycombosign.setFixedWidth(40)
        self.buycombosign.setFont(QFont("仿宋", 10))
        self.buyedit = QPlainTextEdit()
        self.buyedit.setFixedSize(80,30)
        self.buyedit.setFont(QFont("仿宋", 10))
        self.buyaddbtn = QPushButton()
        self.buyaddbtn.setText("添加")
        self.buyaddbtn.setFixedSize(80, 30)
        self.buyaddbtn.setFont(QFont("仿宋", 10))
        self.buyclearbtn = QPushButton()
        self.buyclearbtn.setText("清除所有条件")
        self.buyclearbtn.setFixedSize(120, 30)
        self.buyclearbtn.setFont(QFont("仿宋", 10))
        self.buytb = QTextBrowser()
        self.buytb.setFixedSize(250, 100)

        self.selllabel = QLabel()
        self.selllabel.setText("买入条件")
        self.selllabel.setFont(QFont("仿宋", 13))
        self.sellcomboindex = QComboBox()
        self.sellcomboindex.addItems(self.index)
        self.sellcomboindex.setFixedWidth(40)
        self.sellcomboindex.setFont(QFont("仿宋", 10))
        self.sellcombosign = QComboBox()
        self.sellcombosign.addItems(self.sign)
        self.sellcombosign.setFixedWidth(40)
        self.sellcombosign.setFont(QFont("仿宋", 10))
        self.selledit = QPlainTextEdit()
        self.selledit.setFixedSize(80, 30)
        self.selledit.setFont(QFont("仿宋", 10))
        self.selladdbtn = QPushButton()
        self.selladdbtn.setText("添加")
        self.selladdbtn.setFixedSize(80, 30)
        self.selladdbtn.setFont(QFont("仿宋", 10))
        self.sellclearbtn = QPushButton()
        self.sellclearbtn.setText("清除所有条件")
        self.sellclearbtn.setFixedSize(120, 30)
        self.sellclearbtn.setFont(QFont("仿宋", 10))
        self.selltb = QTextBrowser()
        self.selltb.setFixedSize(250, 100)


        self.h11box = QHBoxLayout()
        self.h11box.addWidget(self.pooledit)
        self.h11box.addWidget(self.pooladdbtn)
        self.h11box.addWidget(self.poolclbtn)
        self.h12box = QHBoxLayout()
        self.h12box.addWidget(self.pooltb)

        self.h21box = QHBoxLayout()
        self.h21box.addWidget(self.buycomboindex)
        self.h21box.addWidget(self.buycombosign)
        self.h21box.addWidget(self.buyedit)
        self.h22box = QHBoxLayout()
        self.h22box.addWidget(self.buyaddbtn)
        self.h22box.addWidget(self.buyclearbtn)
        self.h23box = QHBoxLayout()
        self.h23box.addWidget(self.buytb)
        self.h24box = QHBoxLayout()
        self.h24box.addWidget(self.sellcomboindex)
        self.h24box.addWidget(self.sellcombosign)
        self.h24box.addWidget(self.selledit)
        self.h25box = QHBoxLayout()
        self.h25box.addWidget(self.selladdbtn)
        self.h25box.addWidget(self.sellclearbtn)
        self.h26box = QHBoxLayout()
        self.h26box.addWidget(self.selltb)

        self.v1box = QVBoxLayout()
        self.v1box.addStretch(1)
        self.v1box.addWidget(self.poollabel)
        self.v1box.addLayout(self.h11box)
        self.v1box.addLayout(self.h12box)
        self.v1box.addStretch(1)

        self.v2box = QVBoxLayout()
        self.v2box.addStretch(1)
        self.v2box.addWidget(self.buylabel)
        self.v2box.addLayout(self.h21box)
        self.v2box.addLayout(self.h22box)
        self.v2box.addLayout(self.h23box)
        self.v2box.addStretch(1)
        self.v2box.addWidget(self.selllabel)
        self.v2box.addLayout(self.h24box)
        self.v2box.addLayout(self.h25box)
        self.v2box.addLayout(self.h26box)
        self.v2box.addStretch(1)

        self.hbox = QHBoxLayout()
        self.hbox.addStretch(1)
        self.hbox.addLayout(self.v1box)
        self.hbox.addStretch(1)
        self.hbox.addLayout(self.v2box)
        self.hbox.addStretch(1)

        self.setLayout(self.hbox)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    mis = MultiIndexSelection()
    mis.show()
    sys.exit(app.exec_())